    let book1 = document.getElementById("b1");
    let book2 = document.getElementById("b2");
    let book3 = document.getElementById("b3");
    let book4 = document.getElementById("b4");
    let book5 = document.getElementById("b5");
    let book6 = document.getElementById("b6");
    let book7 = document.getElementById("b7");
    let book8 = document.getElementById("b8");
    let book9 = document.getElementById("b9");
    let summary1 = document.getElementById("summary1");
    let summary2 = document.getElementById("summary2");
    let summary3 = document.getElementById("summary3");
    let summary4 = document.getElementById("summary4");
    let summary5 = document.getElementById("summary5");
    let summary6 = document.getElementById("summary6");
    let summary7 = document.getElementById("summary7");
    let summary8 = document.getElementById("summary8");
    let summary9 = document.getElementById("summary9");
    let show1 = document.getElementById("show-summary");
    let hide1 = document.getElementById("hide-summary");
    let show2 = document.getElementById("show1");
    let hide2 = document.getElementById("hide1");
    let show3 = document.getElementById("show3");
    let hide3 = document.getElementById("hide3");
    let show4 = document.getElementById("show4");
    let hide4 = document.getElementById("hide4");
    let show5 = document.getElementById("show5");
    let hide5 = document.getElementById("hide5");
    let show6 = document.getElementById("show6");
    let hide6 = document.getElementById("hide6");
    let show7 = document.getElementById("show7");
    let hide7 = document.getElementById("hide7");
    let show8 = document.getElementById("show8");
    let hide8 = document.getElementById("hide8");
    let show9 = document.getElementById("show9");
    let hide9 = document.getElementById("hide9");
    show1.onclick = function() {
        book1.style.display = "none";
        book2.style.display = "none";
        book3.style.display = "none";
        book4.style.display = "none";
        book5.style.display = "none";
        book6.style.display = "none";
        book7.style.display = "none";
        book8.style.display = "none";
        book9.style.display = "none";
        show1.style.display = "none";
        show2.style.display = "none";
        show3.style.display = "none";
        show4.style.display = "none";
        show5.style.display = "none";
        show6.style.display = "none";
        show7.style.display = "none";
        show8.style.display = "none";
        show9.style.display = "none";
        hide2.style.display = "none";
        hide1.style.display = "block";
        summary1.style.display = "block";
    }
    show2.onclick = function() {
        book1.style.display = "none";
        book2.style.display = "none";
        book3.style.display = "none";
        book4.style.display = "none";
        book5.style.display = "none";
        book6.style.display = "none";
        book7.style.display = "none";
        book8.style.display = "none";
        book9.style.display = "none";
        show2.style.display = "none";
        show1.style.display = "none";
        show3.style.display = "none";
        show4.style.display = "none";
        show5.style.display = "none";
        show6.style.display = "none";
        show7.style.display = "none";
        show8.style.display = "none";
        show9.style.display = "none";
        hide2.style.display = "block";
        summary2.style.display = "block";
    }
    show3.onclick = function() {
        book1.style.display = "none";
        book2.style.display = "none";
        book3.style.display = "none";
        book4.style.display = "none";
        book5.style.display = "none";
        book6.style.display = "none";
        book7.style.display = "none";
        book8.style.display = "none";
        book9.style.display = "none";
        show2.style.display = "none";
        show1.style.display = "none";
        show4.style.display = "none";
        show5.style.display = "none";
        show6.style.display = "none";
        show7.style.display = "none";
        show8.style.display = "none";
        show9.style.display = "none";
        hide2.style.display = "none";
        summary2.style.display = "none";
        show3.style.display = "none";
        hide3.style.display = "block";
        summary3.style.display = "block";
    }
    show4.onclick = function() {
        book1.style.display = "none";
        book2.style.display = "none";
        book3.style.display = "none";
        book4.style.display = "none";
        book5.style.display = "none";
        book6.style.display = "none";
        book7.style.display = "none";
        book8.style.display = "none";
        book9.style.display = "none";
        show2.style.display = "none";
        show1.style.display = "none";
        show4.style.display = "none";
        show5.style.display = "none";
        show6.style.display = "none";
        show7.style.display = "none";
        show8.style.display = "none";
        show9.style.display = "none";
        hide2.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        show3.style.display = "none";
        hide4.style.display = "block";
        summary4.style.display = "block";
    }
    show5.onclick = function() {
        book1.style.display = "none";
        book2.style.display = "none";
        book3.style.display = "none";
        book4.style.display = "none";
        book5.style.display = "none";
        book6.style.display = "none";
        book7.style.display = "none";
        book8.style.display = "none";
        book9.style.display = "none";
        show2.style.display = "none";
        show1.style.display = "none";
        show4.style.display = "none";
        show3.style.display = "none";
        show5.style.display = "none";
        show6.style.display = "none";
        show7.style.display = "none";
        show8.style.display = "none";
        show9.style.display = "none";
        hide2.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        hide5.style.display = "block";
        summary5.style.display = "block";
    }
    show6.onclick = function() {
        book1.style.display = "none";
        book2.style.display = "none";
        book3.style.display = "none";
        book4.style.display = "none";
        book5.style.display = "none";
        book6.style.display = "none";
        book7.style.display = "none";
        book8.style.display = "none";
        book9.style.display = "none";
        show2.style.display = "none";
        show1.style.display = "none";
        show4.style.display = "none";
        show3.style.display = "none";
        show5.style.display = "none";
        show6.style.display = "none";
        show7.style.display = "none";
        show8.style.display = "none";
        show9.style.display = "none";
        hide2.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        hide6.style.display = "block";
        summary6.style.display = "block";
    }
    show7.onclick = function() {
        book1.style.display = "none";
        book2.style.display = "none";
        book3.style.display = "none";
        book4.style.display = "none";
        book5.style.display = "none";
        book6.style.display = "none";
        book7.style.display = "none";
        book8.style.display = "none";
        book9.style.display = "none";
        show2.style.display = "none";
        show1.style.display = "none";
        show4.style.display = "none";
        show3.style.display = "none";
        show5.style.display = "none";
        show6.style.display = "none";
        show7.style.display = "none";
        show8.style.display = "none";
        show9.style.display = "none";
        hide2.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        hide7.style.display = "block";
        summary7.style.display = "block";
    }
    show8.onclick = function() {
        book1.style.display = "none";
        book2.style.display = "none";
        book3.style.display = "none";
        book4.style.display = "none";
        book5.style.display = "none";
        book6.style.display = "none";
        book7.style.display = "none";
        book8.style.display = "none";
        book9.style.display = "none";
        show2.style.display = "none";
        show1.style.display = "none";
        show4.style.display = "none";
        show3.style.display = "none";
        show5.style.display = "none";
        show6.style.display = "none";
        show7.style.display = "none";
        show8.style.display = "none";
        show9.style.display = "none";
        hide2.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        hide8.style.display = "block";
        summary8.style.display = "block";
    }
    show9.onclick = function() {
        book1.style.display = "none";
        book2.style.display = "none";
        book3.style.display = "none";
        book4.style.display = "none";
        book5.style.display = "none";
        book6.style.display = "none";
        book7.style.display = "none";
        book8.style.display = "none";
        book9.style.display = "none";
        show2.style.display = "none";
        show1.style.display = "none";
        show4.style.display = "none";
        show3.style.display = "none";
        show5.style.display = "none";
        show6.style.display = "none";
        show7.style.display = "none";
        show8.style.display = "none";
        show9.style.display = "none";
        hide2.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        hide9.style.display = "block";
        summary9.style.display = "block";
    }

    hide1.onclick = function() {
        book1.style.display = "block";
        book2.style.display = "block";
        book3.style.display = "block";
        book4.style.display = "block";
        book5.style.display = "block";
        book6.style.display = "block";
        book7.style.display = "block";
        book8.style.display = "block";
        book9.style.display = "block";
        show1.style.display = "block";
        show2.style.display = "block";
        show3.style.display = "block";
        show4.style.display = "block";
        show5.style.display = "block";
        show6.style.display = "block";
        show7.style.display = "block";
        show8.style.display = "block";
        show9.style.display = "block";
        hide1.style.display = "none";
        summary1.style.display = "none";
    }
    hide2.onclick = function() {
        book1.style.display = "block";
        book2.style.display = "block";
        book3.style.display = "block";
        book4.style.display = "block";
        book5.style.display = "block";
        book6.style.display = "block";
        book7.style.display = "block";
        book8.style.display = "block";
        book9.style.display = "block";
        show2.style.display = "block";
        show3.style.display = "block";
        show4.style.display = "block";
        show5.style.display = "block";
        show6.style.display = "block";
        show7.style.display = "block";
        show8.style.display = "block";
        show9.style.display = "block";
        hide2.style.display = "none";
        show1.style.display = "block";
        hide1.style.display = "none";
        summary2.style.display = "none";
    }
    hide3.onclick = function() {
        book1.style.display = "block";
        book2.style.display = "block";
        book3.style.display = "block";
        book4.style.display = "block";
        book5.style.display = "block";
        book6.style.display = "block";
        book7.style.display = "block";
        book8.style.display = "block";
        book9.style.display = "block";
        show2.style.display = "block";
        show4.style.display = "block";
        show5.style.display = "block";
        show6.style.display = "block";
        show7.style.display = "block";
        show8.style.display = "block";
        show9.style.display = "block";
        hide2.style.display = "none";
        show1.style.display = "block";
        hide1.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        hide3.style.display = "none";
        show3.style.display = "block";
    }
    hide4.onclick = function() {
        book1.style.display = "block";
        book2.style.display = "block";
        book3.style.display = "block";
        book4.style.display = "block";
        book5.style.display = "block";
        book6.style.display = "block";
        book7.style.display = "block";
        book8.style.display = "block";
        book9.style.display = "block";
        show2.style.display = "block";
        show4.style.display = "block";
        show3.style.display = "block";
        show5.style.display = "block";
        show6.style.display = "block";
        show7.style.display = "block";
        show8.style.display = "block";
        show9.style.display = "block";
        hide2.style.display = "none";
        show1.style.display = "block";
        hide1.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        summary4.style.display = "none";
        hide4.style.display = "none";
    }
    hide5.onclick = function() {
        book1.style.display = "block";
        book2.style.display = "block";
        book3.style.display = "block";
        book4.style.display = "block";
        book5.style.display = "block";
        book6.style.display = "block";
        book7.style.display = "block";
        book8.style.display = "block";
        book9.style.display = "block";
        show2.style.display = "block";
        show4.style.display = "block";
        show3.style.display = "block";
        show5.style.display = "block";
        show6.style.display = "block";
        show7.style.display = "block";
        show8.style.display = "block";
        show9.style.display = "block";
        hide2.style.display = "none";
        show1.style.display = "block";
        hide1.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        summary5.style.display = "none";
        hide5.style.display = "none";
    }
    hide6.onclick = function() {
        book1.style.display = "block";
        book2.style.display = "block";
        book3.style.display = "block";
        book4.style.display = "block";
        book5.style.display = "block";
        book6.style.display = "block";
        book7.style.display = "block";
        book8.style.display = "block";
        book9.style.display = "block";
        show2.style.display = "block";
        show4.style.display = "block";
        show3.style.display = "block";
        show5.style.display = "block";
        show6.style.display = "block";
        show7.style.display = "block";
        show8.style.display = "block";
        show9.style.display = "block";
        hide2.style.display = "none";
        show1.style.display = "block";
        hide1.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        summary6.style.display = "none";
        hide6.style.display = "none";
    }
    hide7.onclick = function() {
        book1.style.display = "block";
        book2.style.display = "block";
        book3.style.display = "block";
        book4.style.display = "block";
        book5.style.display = "block";
        book6.style.display = "block";
        book7.style.display = "block";
        book8.style.display = "block";
        book9.style.display = "block";
        show2.style.display = "block";
        show4.style.display = "block";
        show3.style.display = "block";
        show5.style.display = "block";
        show6.style.display = "block";
        show7.style.display = "block";
        show8.style.display = "block";
        show9.style.display = "block";
        hide2.style.display = "none";
        show1.style.display = "block";
        hide1.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        summary7.style.display = "none";
        hide7.style.display = "none";
    }
    hide8.onclick = function() {
        book1.style.display = "block";
        book2.style.display = "block";
        book3.style.display = "block";
        book4.style.display = "block";
        book5.style.display = "block";
        book6.style.display = "block";
        book7.style.display = "block";
        book8.style.display = "block";
        book9.style.display = "block";
        show2.style.display = "block";
        show4.style.display = "block";
        show3.style.display = "block";
        show5.style.display = "block";
        show6.style.display = "block";
        show7.style.display = "block";
        show8.style.display = "block";
        show9.style.display = "block";
        hide2.style.display = "none";
        show1.style.display = "block";
        hide1.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        summary8.style.display = "none";
        hide8.style.display = "none";
    }
    hide9.onclick = function() {
        book1.style.display = "block";
        book2.style.display = "block";
        book3.style.display = "block";
        book4.style.display = "block";
        book5.style.display = "block";
        book6.style.display = "block";
        book7.style.display = "block";
        book8.style.display = "block";
        book9.style.display = "block";
        show2.style.display = "block";
        show4.style.display = "block";
        show3.style.display = "block";
        show5.style.display = "block";
        show6.style.display = "block";
        show7.style.display = "block";
        show8.style.display = "block";
        show9.style.display = "block";
        hide2.style.display = "none";
        show1.style.display = "block";
        hide1.style.display = "none";
        summary2.style.display = "none";
        summary3.style.display = "none";
        summary9.style.display = "none";
        hide9.style.display = "none";
    }
    function changeTheme(){
        var stylesheet=document.getElementById('stylesheet');
        if(stylesheet.href.endsWith('master.css'))
        {
            stylesheet.href='./css/theme1.css';
        }
        else
        {
            stylesheet.href='./css/master.css';
        }
    }
    function changeTheme2(){
        var stylesheet=document.getElementById('stylesheet');
        if(stylesheet.href.endsWith('master.css'))
        {
            stylesheet.href='../css/theme1.css';
        }
        else
        {
            stylesheet.href='../css/master.css';
        }
    }
    function showsidepar(){
        const sidebar=document.querySelector(".sidepar")
        sidebar.style.display="flex";
    }
    function hidesidebar(){
        const sidebar=document.querySelector(".sidepar")
        sidebar.style.display="none";
    }
    